#!/usr/bin/env bash
#
# release-scope.sh — Kerosene release scoping helper.
#
# Runs inside CI (or locally) to answer three questions driving the automated
# release pipeline:
#
#   1. Is there anything to release?  (commits since the last release tag)
#   2. What is the next semantic version?  (derived from conventional commits)
#   3. What should the changelog say?      (git log since last release tag)
#
# It NEVER mutates the repo. It prints a shell-evaluable block of KEY=VALUE
# lines to stdout (safe to `eval "$(./scripts/release-scope.sh ...)"`), plus a
# human-readable changelog section. Exit codes:
#   0  -> a release is warranted; TAGS/NEXT_VERSION/... are set
#   1  -> nothing to release (no new commits); callers should no-op
#   2  -> configuration / tooling error
#
# Conventional-commit scoping (no breaking commits => patch/minor logic):
#   - `feat`            -> minor bump
#   - `feat(scope)!`    -> major bump
#   - `fix`             -> patch bump
#   - anything else     -> patch bump (default; conservative)
#
# Pre: `git` available, run from repo root. Set RELEASE_FORCE=1 to ignore the
# "new commits?" check (useful for initial backfill / retries).

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

echo_nokey() { echo "$*"; }

# ---------------------------------------------------------------------------
# Find the most recent release tag matching v<semver> (strict dot.separated).
# Non-semver tags like `latest`, `ui`, `initial` are ignored deliberately.
# ---------------------------------------------------------------------------
find_last_tag() {
    git tag --list 'v[0-9]*.[0-9]*.[0-9]*' \
        | grep -E '^v[0-9]+(\.[0-9]+){2}(-[0-9A-Za-z.-]+)?$' \
        | sort -V \
        | tail -1 || true
}

# ---------------------------------------------------------------------------
# Determine the highest bump level warranted by the commit range.
# ---------------------------------------------------------------------------
bump_level() {
    local range="$1"
    local level="patch"

    # A breaking change (commit subject contains '!' before ':' or the word
    # BREAKING) forces a major bump.
    if git log --format='%s' "$range" \
        | grep -qE '(^|\)!)!|BREAKING'; then
        echo "major"
        return
    fi
    # Any feature commit forces a minor bump.
    if git log --format='%s' "$range" \
        | grep -qE '^feat(\([^)]*\))?!?:'; then
        echo "minor"
        return
    fi
    echo "$level"
}

# ---------------------------------------------------------------------------
# Increment a semver string by the given level. Supports pre-release suffixes
# on the CURRENT version (drops them for the next stable). Handles 0.x semantics
# naturally (0.y minor -> 0.(y+1)).
# ---------------------------------------------------------------------------
bump_version() {
    local current="$1"
    local level="$2"
    local major minor patch
    # Strip any pre-release/build metadata from the current version.
    major="${current%%.[0-9]*}"
    current_no_pre="${current#*v}"
    current_no_pre="${current_no_pre%%-*}"
    current_no_pre="${current_no_pre%%+*}"
    IFS='.' read -r major minor patch <<<"$current_no_pre"

    case "$level" in
        major) major=$((major + 1)); minor=0; patch=0 ;;
        minor) minor=$((minor + 1)); patch=0 ;;
        patch) patch=$((patch + 1)) ;;
        *) patch=$((patch + 1)) ;;
    esac
    echo "${major}.${minor}.${patch}"
}

# ---------------------------------------------------------------------------
# Build a readable changelog from the commit range.
# ---------------------------------------------------------------------------
build_changelog() {
    local range="$1"
    local out="$2"
    {
        echo "## What's changed"
        echo ""
        echo "Autogenerated from commits \`${range}\`."
        echo ""
        git log --format='- %s (%h)' "$range" 2>/dev/null \
            || echo "- (no commit list available)"
    } > "$out"
}

usage() {
    cat <<EOF
Usage: $(basename "$0") [--json]

Prints the release-scope decision to stdout.

Environment:
  RELEASE_FORCE=1   ignore the "new commits?" check (backfill / retry)
EOF
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
MODE="text"
if [ "${1:-}" = "--json" ]; then
    MODE="json"
elif [ -n "${1:-}" ]; then
    # allow extra args like --version flags; here we only know --json
    :
fi

LAST_TAG="$(find_last_tag)"
if [ -z "$LAST_TAG" ]; then
    # No release tag yet. Treat everything as the initial release.
    RANGE=""
    INITIAL_BUMP="major"
    INITIAL_VERSION="$(bump_version "0.0.0" "$INITIAL_BUMP")"
    INITIAL_TAG="v${INITIAL_VERSION}"
    # If a tag already exists (retry after a partial publish), reuse it.
    if git rev-parse --verify --quiet "refs/tags/${INITIAL_TAG}" >/dev/null 2>&1; then
        echo_nokey "VERSION_EXISTS=1"
        echo_nokey "BUMP=reuse"
    else
        echo_nokey "VERSION_EXISTS=0"
        echo_nokey "BUMP=$INITIAL_BUMP"
    fi
    echo_nokey "HAS_RELEASES=0"
    echo_nokey "LAST_TAG="
    echo_nokey "RANGE="
    echo_nokey "NEXT_VERSION=$INITIAL_VERSION"
    echo_nokey "NEXT_TAG=$INITIAL_TAG"
    echo_nokey "RELEASE_NOTES=First automated release of Kerosene."
    exit 0
fi

RANGE="${LAST_TAG}..HEAD"

if [ "${RELEASE_FORCE:-0}" != "1" ]; then
    NEW_COUNT="$(git rev-list --count "$RANGE" 2>/dev/null || echo 0)"
    if [ "$NEW_COUNT" -eq 0 ]; then
        echo_nokey "HAS_RELEASES=0"
        echo_nokey "LAST_TAG=$LAST_TAG"
        echo_nokey "RANGE=$RANGE"
        echo_nokey "NEW_COUNT=$NEW_COUNT"
        echo_nokey "NEXT_VERSION="
        exit 1
    fi
fi

BUMP="$(bump_level "$RANGE")"
CURRENT="${LAST_TAG#v}"
NEXT_VERSION="$(bump_version "$LAST_TAG" "$BUMP")"
NEXT_TAG="v${NEXT_VERSION}"

# If a tag for the computed next version already exists, a previous run
# bumped it but never finished publishing (or published and we're re-running).
# In that case we reuse the existing version rather than bumping again.
if git rev-parse --verify --quiet "refs/tags/${NEXT_TAG}" >/dev/null 2>&1; then
    # Already bumped; build + publish this existing version.
    echo_nokey "VERSION_EXISTS=1"
    echo_nokey "BUMP=reuse"
else
    echo_nokey "VERSION_EXISTS=0"
fi

# Build changelog to a temp file and inline it.
CHANGELOG_FILE="$(mktemp)"
build_changelog "$RANGE" "$CHANGELOG_FILE"
CHANGELOG="$(cat "$CHANGELOG_FILE")"
rm -f "$CHANGELOG_FILE"

if [ "$MODE" = "json" ]; then
    # Shell-escape the changelog into a single JSON string.
    ESCAPED="$(printf '%s' "$CHANGELOG" | python3 -c 'import sys,json;print(json.dumps(sys.stdin.read()))' 2>/dev/null \
        || printf '%s' "$CHANGELOG" | sed 's/\\/\\\\/g; s/"/\\"/g; s/$/\\n/')"
    VERSION_EXISTS="${VERSION_EXISTS:-0}"
    cat <<EOF
{
  "has_release": true,
  "last_tag": "$LAST_TAG",
  "range": "$RANGE",
  "next_version": "$NEXT_VERSION",
  "next_tag": "$NEXT_TAG",
  "version_exists": "$VERSION_EXISTS",
  "bump": "$BUMP",
  "new_commit_count": $(git rev-list --count "$RANGE"),
  "release_notes": $ESCAPED
}
EOF
else
    echo_nokey "HAS_RELEASES=1"
    echo_nokey "LAST_TAG=$LAST_TAG"
    echo_nokey "RANGE=$RANGE"
    echo_nokey "NEW_COUNT=$(git rev-list --count "$RANGE")"
    echo_nokey "NEXT_VERSION=$NEXT_VERSION"
    echo_nokey "NEXT_TAG=$NEXT_TAG"
    echo_nokey "VERSION_EXISTS=${VERSION_EXISTS:-0}"
    echo_nokey "BUMP=$BUMP"
    # Emit the changelog as a single, escaped line under RELEASE_NOTES= ...
    echo_nokey "RELEASE_NOTES=$(printf '%s' "$CHANGELOG" | sed 's/\\n/\\\\n/g' | sed 's/"/\\"/g')"
fi

exit 0
